version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongo-loan
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Saad0125
      MONGO_INITDB_DATABASE: fake-loan-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro


volumes:
  mongodb_data:
